language: node_js

node_js: stable

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn build:doc

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master